### ISSUE TITLE
"Server" Questions

### ISSUE THREAD

**Issue by Mins0o** [jirheee/CS492-Team-Project#8]
Questions regarding developing and running the "Server".

**Comment by jirheee** [comment]
Wassup

**Comment by Mins0o** [comment]
![image](https://user-images.githubusercontent.com/52537526/140025516-aa1ebdb8-86e4-4051-ad28-8df4d95b0b95.png)

I ran 
`$env:DB_USERNAME="Minsoo" \
$env:DB_ROOT_PASSWORD="password" \
$env:DB_PASSWORD="password_" \
$env:MAINDB_NAME="Minsoo"`
`docker-compose -f docker-compose.yml up`
in my Windows Powershell, and seems like the `cs492i-api-server` is having some troubles. Is this a problem?

**Comment by Mins0o** [comment]
> ```
> $env:DB_USERNAME="Minsoo" 
> $env:DB_ROOT_PASSWORD="password" 
> $env:DB_PASSWORD="password_" 
> $env:MAINDB_NAME="Minsoo"
> ```

Ah I realized there is `env.example` file.

**Comment by jirheee** [comment]
You should run `cp .env.example .env` first to create .env file!

**Comment by Mins0o** [comment]
Will I still need to follow the README.md?
```
pip install fastapi
pip install 'uvicorn[standard]'
pip install python-socketio
```

**Comment by jirheee** [comment]
Nope it's from the python boilerplate code. I will update the README ASAP

**Comment by jirheee** [comment]
Oh so I didn't update the README. to run the server, you can just use `docker-compose up` command. You have nothing to configure manually now. Sorry for the inconvenience.

**Comment by Mins0o** [comment]
> You should run `cp .env.example .env` first to create .env file!
Still when I run `docker-compose -f docker-compose.yml up`, I get the error as:
```
cs492i-api-server  | standard_init_linux.go:228: exec user process caused: no such file or directory
cs492i-api-server exited with code 0
cs492i-api-server exited with code 1
cs492i-api-server exited with code 1
cs492i-api-server exited with code 1
...
...
```

**Comment by jirheee** [comment]
What branch are you at currently?

**Comment by Mins0o** [comment]
main.
Should I run `yarn start` first?

**Comment by jirheee** [comment]
Can you post a screenshot of your local server directory?

**Comment by jirheee** [comment]
Well I guess yarn is not the problem since it runs yarn start at entrypoint.sh

**Comment by Mins0o** [comment]
> Can you post a screenshot of your local server directory?

![image](https://user-images.githubusercontent.com/52537526/140028514-3c3caba0-7998-4c92-8c58-bf15462c7094.png)

**Comment by jirheee** [comment]
I think you should try with this command `docker-compose up --build`

**Comment by jirheee** [comment]
I think the .env file is not in the built image happened because you build the container before making .env file

**Comment by Mins0o** [comment]
> I think you should try with this command `docker-compose up --build`

Still no luck :(

**Comment by Mins0o** [comment]
I detached the volume and re-ran the `docker-compose up --build`.  
I have more info with the "initial run" now... let me get back to you later!  
  
Thanks for the help.

**Comment by Mins0o** [comment]
I have one volume present, is this normal?
![image](https://user-images.githubusercontent.com/52537526/140032177-e51e1426-c28e-4707-ae12-f1e4ffcb8182.png)

**Comment by Mins0o** [comment]
I got it successfully running on my Linux machine, which is very very slow.
I'll figure out how I can run this on my own machine later

**Comment by jirheee** [comment]
> I have one volume present, is this normal?

There should be one volume, one used by the mysql container. So I think it's right.
Can you show me the error log it prints out?

**Comment by Mins0o** [comment]
Ahrrraaggggghhhhhhghghhhh I found out what was causing the problem.  
  
The error: `standard_init_linux.go:228: exec user process caused: no such file or directory`  
  
  
Turns out, Windows and Linux has different line ending scheme. IT WAS LITERALLY A BUG THAT IS INVISIBLE TO NAKED EYES.
>[DOS uses carriage return and line feed ("\r\n") as a line ending, which Unix uses just line feed ("\n")](https://www.cs.toronto.edu/~krueger/csc209h/tut/line-endings.html#:~:text=DOS%20uses%20carriage%20return%20and%20line%20feed%20(%22%5Cr%5Cn%22)%20as%20a%20line%20ending%2C%20which%20Unix%20uses%20just%20line%20feed%20(%22%5Cn%22))  
  
  
  
You can [easily change the file influenced file in VSCode](https://stackoverflow.com/questions/39525417/visual-studio-code-how-to-show-line-endings#:~:text=in%20the%20bottom-right%20corner%20of%20the%20window%20there%20is%20an%20indicator%20that%20says%20%22CLRF%22%20or%20%22LF%22%20which%20will%20let%20you%20set%20the%20line%20endings%20for%20a%20particular%20file.%20Clicking%20on%20the%20text%20will%20allow%20you%20to%20change%20the%20line%20endings%20as%20well.).  
  
Or [change your git settings](https://docs.github.com/en/get-started/getting-started-with-git/configuring-git-to-handle-line-endings#:~:text=different%20operating%20systems.-,Global%20settings%20for%20line%20endings,-The%20git%20config) where it automatically converted all the `\n` to `\r\n`. 😠 💢   
  
  
There must be a way for Docker Desktop to make this transition automatic when copying `.sh` into a linux container @docker ...

**Comment by jirheee** [comment]
Oh so the `entrypoint.sh` is copied into docker image with carriage return("\r\n")...?
Or is it "\n" converted into "\r\n" at git pulling stage?

**Comment by Mins0o** [comment]
This has bug.  
![image](https://user-images.githubusercontent.com/52537526/140272817-5879ded2-3909-4948-b0f1-cf145ef58ae7.png)
  
---
This is fixed.  
![image](https://user-images.githubusercontent.com/52537526/140272844-0b6c07ee-4b26-455b-89a5-7229d9afb874.png)
  
  
The fix: ![image](https://user-images.githubusercontent.com/52537526/140273307-051b59b6-0ca2-4db5-941c-2d7f1fd3b96b.png) => ![image](https://user-images.githubusercontent.com/52537526/140273331-9c449277-b98c-409e-8e77-f936289934c4.png)

**Comment by Mins0o** [comment]
> Oh so the `entrypoint.sh` is copied into docker image with carriage return("\r\n")...?
  Or is "\n" being converted into "\r\n" at git pulling stage?
  
At the git pulling stage.  
  
I wrote my rant over it hoping to help another poor soul who might suffer from it lol 😆

**Comment by jirheee** [comment]
I hate this kind of implicit things happening out of user's perception 🥲
It is almost impossible to debug things if you don't know that can actually happen...
I think @dbsxodud-11 should refer to this issue if there is something awkward happening while running the server. Can you edit the README file in [server directory](https://github.com/jirheee/CS492-Team-Project/tree/main/Server#cs492-team-project-client) for @dbsxodud-11 to refer to?

**Comment by Mins0o** [comment]
> Can you edit the README file

Will do!

**Comment by jirheee** [comment]
Thanks!
