### ISSUE TITLE
Case sensitive directory name colliding with codes

### ISSUE THREAD

**Issue by Mins0o** [jirheee/CS492-Team-Project#9]
I have no problem now by changing the directories' names into lower case, so it's not really a big problem.  
Just thought it's worth mentioning.

I don't know how to fix this with git commits, but the fact that the directory names `./Client/src/Components` and `./Client/src/Pages` are uppercase cause problem because codes refer to them in lowercase.
  
vvv In ./Client/src/Pages/agentIndexPage.tsx vvv
```
import BaseIndexPage from '../components/baseIndexPage';
import HoverBtn from '../components/hoverBtn';
```
the `components` are referred with lower case here.  
This caused some `File not found` errors.

**Comment by jirheee** [comment]
I think it is because of case insensitivity of Mac or git(don't know whoever it is).
Should we just update the imports to Uppercase in the remote repo too?
